### ISSUE TITLE
Add section on dependency management for Spring Data modules and Spring Framework to the reference documentation [DATACMNS-687]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1154]
**[Caleb Cushing](https://jira.spring.io/secure/ViewProfile.jspa?name=xenoterracide)** opened **[DATACMNS-687](https://jira.spring.io/browse/DATACMNS-687?redirect=false)** and commented

I'm having trouble telling if this is a valid bug from the documentation because I'm not sure if Spring Data 1.7+ should actually work on 3.2, but it does say that it should work without spring so I assume Spring 3.2 is a valid target. This error does not exist in 1.6.5

I'm getting the following exception trying to autowire an empty repository (meaning I haven't defined additional methods) that extends PagingAndSortingRepository

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'organizationActivityLogDtoSupplier' defined in file [/Users/ccushing/IdeaProjects/dex/dex-service-api/target/classes/com/mckesson/dex/service/resource/OrganizationActivityLogDtoSupplier.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.mckesson.dex.repository.OrganizationActivityLogRepository]: : Error creating bean with name 'organizationActivityLogRepository': Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/DefaultParameterNameDiscoverer; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'organizationActivityLogRepository': Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/DefaultParameterNameDiscoverer
```

---

**Affects:** 1.8.5 (Dijkstra SR5), 1.9.2 (Evans SR2), 1.10 GA (Fowler)

**Issue Links:**
- [DATAJPA-714](https://jira.spring.io/browse/DATAJPA-714) Include new section on Spring Data and Spring Framework dependencies in reference documentation

- [DATAMONGO-1213](https://jira.spring.io/browse/DATAMONGO-1213) Include new section on Spring Data and Spring Framework dependencies in reference documentation

**Backported to:** [1.10.1 (Fowler SR1)](https://github.com/spring-projects/spring-data-commons/milestone/64?closed=1), [1.9.3 (Evans SR3)](https://github.com/spring-projects/spring-data-commons/milestone/63?closed=1)
